---
title: East Coast Kelly
tagline: 'I help busy moms simplify and prioritize routines, to do lists, home management '
description: "Helping busy moms \U0001D494\U0001D48A\U0001D48E\U0001D491\U0001D48D\U0001D48A\U0001D487\U0001D49A
  + \U0001D491\U0001D493\U0001D48A\U0001D490\U0001D493\U0001D48A\U0001D495\U0001D48A\U0001D49B\U0001D486"
url: 'www.eastcoastkelly.com '
baseurl: ''
author:
  name: Kelly Briggs
  url: ''
paginate: 4
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-menus
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: kramdown
highlighter: rouge
facebook: https://www.facebook.com/kelly.briggs
twitter: ''
instagram: https://www.instagram.com/eastcoastkelly/
