---
title: East Coast Kelly
tagline: I help busy moms simplify managing their homes with intentional planning
  + prioritizing
description: Helping busy moms simplify
url: 'www.eastcoastkelly.com '
baseurl: ''
author:
  name: Kelly Briggs
  url: ''
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-menus
sidebar_home_link: false
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
theme: jekyll-theme-hydeout
markdown: kramdown
highlighter: rouge
facebook: https://www.facebook.com/kelly.briggs
twitter: ''
instagram: https://www.instagram.com/eastcoastkelly/
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: www-eastcoastkelly-com