---
title: East Coast Kelly
tagline: Simple Living
description: Helping busy moms prioritize the to do list & reduce the daily load by
  using simple living tips.
url: https://flamboyant-mccarthy-691f26.netlify.com/
baseurl: ''
author:
  name: Kelly Briggs
  url: ''
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-menus
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#1C1408"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: kramdown
highlighter: rouge
facebook: https://www.facebook.com/kelly.briggs
twitter: ''
instagram: https://www.instagram.com/eastcoastkelly/
